============================= test session starts ==============================
platform darwin -- Python 3.10.6, pytest-7.4.3, pluggy-1.3.0 -- /Users/tanushrinayak/.pyenv/versions/3.10.6/envs/taxifare-env/bin/python3.10
cachedir: .pytest_cache
rootdir: /Users/tanushrinayak/code/tanushrin/07-ML-Ops/03-Automate-model-lifecycle/data-model-lifecycle/tests
configfile: pytest_kitt.ini
plugins: anyio-3.7.1
collecting ... collected 6 items / 1 error

==================================== ERRORS ====================================
__________________ ERROR collecting lifecycle/test_prefect.py __________________
ImportError while importing test module '/Users/tanushrinayak/code/tanushrin/07-ML-Ops/03-Automate-model-lifecycle/data-model-lifecycle/tests/lifecycle/test_prefect.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../.pyenv/versions/3.10.6/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/lifecycle/test_prefect.py:6: in <module>
    from taxifare.interface.workflow import *
taxifare/interface/workflow.py:6: in <module>
    from prefect import task, flow
../../../../../.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/prefect/__init__.py:25: in <module>
    from prefect.states import State
../../../../../.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/prefect/states.py:14: in <module>
    from prefect.client.schemas import State as State
../../../../../.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/prefect/client/schemas.py:6: in <module>
    from prefect.server import schemas
../../../../../.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/prefect/server/__init__.py:1: in <module>
    from . import models
../../../../../.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/prefect/server/models/__init__.py:1: in <module>
    from . import (
../../../../../.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/prefect/server/models/block_documents.py:13: in <module>
    from prefect.server import schemas
../../../../../.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/prefect/server/schemas/__init__.py:1: in <module>
    from . import states, schedules, core, sorting, filters, responses, actions
../../../../../.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/prefect/server/schemas/states.py:13: in <module>
    from prefect.server.utilities.schemas import DateTimeTZ, IDBaseModel, PrefectBaseModel
../../../../../.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/prefect/server/utilities/schemas.py:17: in <module>
    from pydantic import BaseModel, Field, SecretField
E   ImportError: cannot import name 'SecretField' from 'pydantic' (/Users/tanushrinayak/.pyenv/versions/3.10.6/envs/taxifare-env/lib/python3.10/site-packages/pydantic/__init__.py)
=========================== short test summary info ============================
ERROR tests/lifecycle/test_prefect.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 3.52s ===============================
